In [39]:
#_NumPy Python'da bilimsel hesaplamalar yapabilmek için kullanılan bir kütüphanedir._ 
#NumPy tek tip veri kullanır.
#NumPy import etmek.

In [4]:
import numpy as np

In [6]:
#Numpy Array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [48]:
#***********************Sıfırdan array oluşturmak*****************
#10 tane 0 olan array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#1'lerden olusan 3'e 5'lik array
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#İstediğimiz sayılardan oluşturmak istediğimiz array
#yine 3'e 5'lik 7'lerden olan np arrayi
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
#Doğrusal array oluşturmak
#0'dan 31'e kadan 3'er 3'er arkan doğrusal array
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [15]:
#İki değer arasında 10 elemanlı doğrusal array
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
#Ortalaması 10 standart sapması 4 olan 3'e 5'lik array
np.random.normal(10,4,(3,4))

array([[13.47249223, 11.46198636, 10.66109914,  9.96625943],
       [ 7.73274667,  7.10182831,  5.60316688, 11.9986208 ],
       [ 5.14401649,  6.22178129, 11.03160567,  0.94861155]])

In [17]:
#Rastgele 0 ile 10 arasında 3'e 3 integer değer üretme
np.random.randint(0,10,(3,3))

array([[1, 2, 6],
       [3, 1, 9],
       [9, 5, 4]])

In [111]:
#**********************NUMPY ARRAY ÖZELİKKLERİ******************#
#ndim:Boyut sayisi bulma.
#shapeBoyut bilgisi bulma.
#size:toplam eleman satısını bulma
#type:array ver tipini öğrenme.    
    

In [34]:
a=np.random.randint(10,size=(3,5))

In [35]:
a.ndim

2

In [36]:
a.shape

(3, 5)

In [37]:
a.size

15

In [38]:
a.dtype

dtype('int32')

In [44]:
#************NumPy Array Yeniden şekillendirme(Reshaping)**********

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#Tek boyutlu numpy arrayini 3e3 lük bir aray e dönüştürmek
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a=np.arange(1,10)

In [51]:
a.ndim

1

In [52]:
#Vektörü 2 boyutlu hale gerimek,yani her satırda bir eleman demektir
b=a.reshape((1,9))

In [54]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
b.ndim

2

In [56]:
#**********Array Birleştirme(Cancatenation)**************#

In [58]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [59]:
#iki arrrayi birleştirdi
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [60]:
z=np.array([7,8,9])


In [61]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#İki boyutlularda birleştirme

In [63]:
a=np.array([[1,2,3],
            [4,5,6]])

In [66]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
#Sütün ve satır bazında birleştirme

In [68]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [69]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
#*******************Array Ayırma(Splitting)************#

In [73]:
x=np.array([1,2,3,99,99,3,2,1])

In [75]:
#0 dan 3'e-3'den 'e-5den sona kadar arrayı ayır 
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [76]:
#Yine aynı ilemi yap fakat parçanılan arrayı a,b ve c değişkenine ata.
a,b,c=np.split(x,[3,5])

In [78]:
a

array([1, 2, 3])

In [79]:
b

array([99, 99])

In [80]:
c

array([3, 2, 1])

In [81]:
#İki boyutlu ayırma

In [82]:
m=np.arange(16).reshape(4,4)

In [84]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
#Arrayi 2.indexten ayır bölünen arayi alt ve üst değişkenine ata.
ust,alt=np.vsplit(m,[2])

In [87]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
#2boyutlu arrayi dikey bölmek

In [90]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [92]:
#**************************Sıralama(Sorting)*****************#

In [93]:
v=np.array([2,1,4,3,5])

In [94]:
v

array([2, 1, 4, 3, 5])

In [95]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [96]:
#yapılan değişiklik ana arrayi etkilemez

In [97]:
v

array([2, 1, 4, 3, 5])

In [98]:
v.sort() #bu şekilde yapılırsa ana array değişir

In [99]:
v

array([1, 2, 3, 4, 5])

In [100]:
#İki boyutlu array sıralama

In [109]:
#Ortalaması 20 standart sapması 5 olan matris oluşturduk
m=np.random.normal(20,5,(3,3))
m

array([[15.86192019, 18.40509742, 20.74078403],
       [25.5101721 , 17.81981943, 17.50721799],
       [22.26814874, 14.982927  , 15.72921599]])

In [106]:
#Dikey sıralama
np.sort(m,axis=0)

array([[15.10922871, 15.4688989 , 11.43600095],
       [15.34670693, 23.52265756, 21.75855233],
       [22.78377542, 27.65000479, 23.67136347]])

In [110]:
#Yatay sıralama
np.sort(m,axis=1)

array([[15.86192019, 18.40509742, 20.74078403],
       [17.50721799, 17.81981943, 25.5101721 ],
       [14.982927  , 15.72921599, 22.26814874]])

In [112]:
#************İndex ile elemanlara Erişmek****************#

In [114]:
a=np.random.randint(10,size=10)
a

array([8, 6, 3, 0, 6, 6, 9, 1, 8, 3])

In [115]:
a[0]=200

In [116]:
a

array([200,   6,   3,   0,   6,   6,   9,   1,   8,   3])

In [117]:
 #********************Array Alt Küme İşlemleri*************#

In [119]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [122]:
#0 dan 3'e kadar git
a[0:3] #(a[:3] ile aynı şey)

array([20, 21, 22])

In [123]:
#3'den sona kadar git
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [127]:
#1.indexdeb başlayarak 2 şer şer atla 
a[1::2]

array([21, 23, 25, 27, 29])

In [128]:
#İki boyutlu slice işlemleri

In [139]:
m=np.random.randint(10 ,size=(5,5))

In [140]:
m

array([[7, 2, 6, 7, 2],
       [5, 5, 4, 5, 0],
       [7, 3, 7, 8, 4],
       [4, 5, 7, 5, 1],
       [7, 5, 3, 8, 3]])

In [144]:
#Tüm satırı ve 0. sütünü seç
m[:,0]

array([7, 5, 7, 4, 7])

In [146]:
#0.satır ve tüm sütünlar
m[0,:]

array([7, 2, 6, 7, 2])

In [148]:
#2.satıra kadar  ve 3.sütüna kardar olan veriler
m[0:2,0:3]

array([[7, 2, 6],
       [5, 5, 4]])

In [154]:
#0 dan 2. stüna kadar olan verileri al
m[::,:2]

array([[7, 2],
       [5, 5],
       [7, 3],
       [4, 5],
       [7, 5]])

In [155]:
m[1:3,0:2]

array([[5, 5],
       [7, 3]])

In [157]:
#copy() metodu ana array üzerinde değişiklik olmaması için kullanılır
m=np.random.randint(10,size=(5,5))

In [158]:
m

array([[4, 5, 3, 2, 7],
       [6, 0, 3, 5, 3],
       [7, 3, 2, 0, 6],
       [3, 7, 9, 5, 1],
       [4, 8, 9, 5, 9]])

In [161]:
alt_b=m[0:3,0:2].copy()

In [162]:
alt_b

array([[4, 5],
       [6, 0],
       [7, 3]])

In [163]:
alt_b[0,0]=99

In [164]:
alt_b

array([[99,  5],
       [ 6,  0],
       [ 7,  3]])

In [165]:
m

array([[4, 5, 3, 2, 7],
       [6, 0, 3, 5, 3],
       [7, 3, 2, 0, 6],
       [3, 7, 9, 5, 1],
       [4, 8, 9, 5, 9]])

In [167]:
#*****************Fancy ile Elemanlara Erişmek************#(Önemli!!!)

In [168]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [172]:
#index göre eleman bulmaya yarar
al_getır=[1,3,5]

In [178]:
v[al_getır]

array([3, 6, 9])

In [179]:
#iki boyutta fancy işlemi
m=np.arange(9).reshape((3,3))

In [180]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [181]:
satir=np.array([0,1])
sütün=np.array([1,2])

In [187]:
m[satir,sütün]

array([0, 4])

In [195]:
#Slice ve Fancy
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [196]:
#*****************Koşullu Eleman işlemleri*********#

In [197]:
v=np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [198]:
v<3

array([ True,  True, False, False, False])

In [200]:
#True değerleri döndürdü
v[v<3]

array([1, 2])

In [201]:
v[v>3]

array([4, 5])

In [203]:
v[v==3]

array([3])

In [204]:
#*****************Matematiksel İşlemler****************#

In [208]:
#arrayden çıkarma işlemi yapar(v arrayinden 1 çıkardı)
np.subtract(v,1
           )

array([-1,  0,  1,  2,  3])

In [209]:
#elemanlra çarpma işlemi yapar(v arrayindeki elemanları 4 ile çarpmış)
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [210]:
#Array elemanlarına toplama işlemi yapar
np.add(v,1)

array([2, 3, 4, 5, 6])

In [211]:
#Array elemanlarına bölme işlemi yapar
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [213]:
#üssünü alır
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [216]:
#mod alma işlemi
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [218]:
#Mutlak değer almak
np.absolute(np.array([-3]))

array([3])

In [219]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\programdata\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>